[package]
name = "plugin-test"
version = "0.0.0"
edition = "2021"

[features]
dynamic = []

[[example]]
name = "hello_world"

[dependencies]
once_cell = "1.15.0"
anyhow = "1.0.65"
const_format = "0.2.5"
parking_lot = "0.12.1"
libloading = "0.7"

[dev-dependencies]
anyhow = "1.0.65"
